### ISSUE TITLE
FR - Wikitude-worlds code in angular

### ISSUE THREAD

**Issue by HardikDG** [Tazaf/IonicitudeDemoApp#8]
Do you have any sample of 'wikitude-worlds' code written in angular?
Almost all the codes Cordova plugin sample and your demo world samples all are written in the JS/jquery. 

If you have any sample with angular for the worlds implementation it will be great.

**Comment by Tazaf** [comment]
Well, technically, you just need to include angular and create a new angular app module on the Wikitude side, since the code of the AR Worlds have no link whatsoever with the code of the Ionic App. You could also include Ionic at the same time, but there's some constraints related to using Ionic features with AR (this has to do with the fact that Ionic pages intercepts screen touching event and thus render interaction with the AR complicated...)

I do have some code of an AR app using Ionic and Wikitude that implements angular on the AR side. You can take a look at the code of this repository : [MediaComem/biosentiers-mobile](https://github.com/MediaComem/biosentiers-mobile), and more specifically in the [`wikitude-worlds` folder](https://github.com/MediaComem/biosentiers-mobile/tree/master/www/wikitude-worlds/main)
But please note that it's a complete project, not an example, so you'd have to crawl a little in the code to make something from it.

When I have some time, I intend to put up a very small sample to illustrate using angular on the AR side. But in the meantime, feel free to check on the above mentionned repo 😄

**Comment by HardikDG** [comment]
Thanks, biosentiers-mobile may help me.
